### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by Chinmay19** [chrischute/glow#1]
I could not understand how do you compute the loss function? Especially the computation of prior_ll part.
It would be great if you could explain what you are doing there

**Comment by chrischute** [comment]
This line computes the log-likelihood of the output `z` assuming a unit-norm Gaussian prior (PDF can be found [here](https://en.wikipedia.org/wiki/Normal_distribution):

```prior_ll = -0.5 * (z ** 2 + np.log(2 * np.pi))```
