### ISSUE TITLE
Generating noise with low BPD and  high NLL

### ISSUE THREAD

**Issue by SrinjaySarkar** [chrischute/glow#10]
In my implementation my BPD and NLL seem to be going down but the quality of the images produced seems to be indistinguishable from plain white noise. 

Epoch 0: bpd=4.84,nll=3.44e+3
Epoch 1: bpd=3.58, nll=2.54e+3
Epoch 20: bpd=2.88, nll=2.04e+3
Epoch 29: bpd=2.83,nll=2.01e+3
This is for the training set , validation remains fairly the same bpd±0.02,nll±0.02
So, I don't think it is overfitting (N=512,L=3,K=32)
The dataset is FashionMNIST .

![epoch0](https://user-images.githubusercontent.com/25768975/112015341-bded7600-8b51-11eb-8a96-41aab46e0625.png)
![epoch1](https://user-images.githubusercontent.com/25768975/112015346-be860c80-8b51-11eb-8cf5-8923ac6a232f.png)
![epoch20](https://user-images.githubusercontent.com/25768975/112015729-14f34b00-8b52-11eb-8a0b-f794f9d73b0c.png)
![epoch29](https://user-images.githubusercontent.com/25768975/112015333-bc23b280-8b51-11eb-96ec-ba57661cc14d.png)

Do I let it train for longer or is it maybe something else?
Would appreciate your input

**Comment by SrinjaySarkar** [comment]
It was my mistake . I was making a forward pass even during the sampling phase (Z==>X)

**Comment by tayalkshitij** [comment]
Dear @SrinjaySarkar ,

I tried MNIST but the reconstruction quality is not good? Is that the case for you also? Can you share some of the reconstructions that you obtained? 

Thank you very much.
