### ISSUE TITLE
about conda and training time

### ISSUE THREAD

**Issue by cbigeyes** [chrischute/glow#3]
Hello,
I can run the code without conda, but it takes me about 6 hours to train an epoch with 2 1080Ti GPUs. I can't figure out what happened. Is this the influence of conda?

**Comment by chrischute** [comment]
Did you check GPU utilization? You probably were training on CPU only.

Conda is just a package manager which will make sure you install the right package versions, including PyTorch with CUDA.

**Comment by cbigeyes** [comment]
I did. The utilization is less than 5%. I don't know how to deal with it. I have run your original code but got the same result.

**Comment by cbigeyes** [comment]
what's your GPU utilization rate?

**Comment by chrischute** [comment]
It should peak at >95% if things are set up properly. Sorry but I can't support other environments besides the provided Conda environment.
