### ISSUE TITLE
Cublas error

### ISSUE THREAD

**Issue by royd1990** [chrischute/glow#7]
The version of pytorch in the environment.yml gives a cublas error:

RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1544176307774/work/aten/src/THC/THCBlas.cu:511

Do you have any idea as to why it occurs?

**Comment by chrischute** [comment]
Please re-open this issue if you're still working on it. Apologies for the late response.
